// property-management/frontend/owner/src/pages/repair/index.jsx
import { useState, useEffect } from 'react'
import { Card, Table, Tag, Button, Modal, Form, Input, Select, Rate, message } from 'antd'
import { ToolOutlined, PlusOutlined, StarOutlined } from '@ant-design/icons'
import { useUserStore } from '../../stores/user'
import { getRepairsByUser, createRepair, cancelRepair, rateRepair } from '../../api'
import { logger } from '../../utils/request'

function Repair() {
  const { userInfo } = useUserStore()
  const [repairs, setRepairs] = useState([])
  const [loading, setLoading] = useState(false)
  const [addModalVisible, setAddModalVisible] = useState(false)
  const [rateModalVisible, setRateModalVisible] = useState(false)
  const [currentRepair, setCurrentRepair] = useState(null)
  const [form] = Form.useForm()
  const [rateForm] = Form.useForm()

  useEffect(() => {
    if (userInfo?.id) {
      loadData()
    }
  }, [userInfo?.id])

  const loadData = async () => {
    if (!userInfo?.id) {
      logger.warn('用户信息不存在，无法加载报修数据')
      return
    }

    setLoading(true)
    logger.info('开始加载报修记录', { userId: userInfo.id })

    try {
      const res = await getRepairsByUser(userInfo.id)
      setRepairs(res.data || [])
      logger.info('报修记录加载成功', { count: res.data?.length || 0 })
    } catch (error) {
      logger.error('加载报修记录失败:', error)
      message.error('加载报修记录失败，请稍后重试')
    } finally {
      setLoading(false)
    }
  }

  const handleAdd = () => {
    form.resetFields()
    setAddModalVisible(true)
  }

  const handleSubmitAdd = async () => {
    try {
      const values = await form.validateFields()
      const data = { ...values, userId: userInfo.id, userName: userInfo.realName }
      logger.info('提交报修申请', data)
      await createRepair(data)
      message.success('报修申请提交成功')
      logger.info('报修申请提交成功')
      setAddModalVisible(false)
      loadData()
    } catch (error) {
      logger.error('提交报修失败', error)
      message.error('提交失败')
    }
  }

  const handleCancel = async (record) => {
    try {
      logger.info('取消报修', { repairId: record.id })
      await cancelRepair(record.id)
      message.success('已取消报修')
      logger.info('取消报修成功')
      loadData()
    } catch (error) {
      logger.error('取消报修失败', error)
      message.error('取消失败')
    }
  }

  const handleRate = (record) => {
    setCurrentRepair(record)
    rateForm.resetFields()
    setRateModalVisible(true)
  }

  const handleSubmitRate = async () => {
    try {
      const values = await rateForm.validateFields()
      logger.info('评价报修服务', { repairId: currentRepair.id, ...values })
      await rateRepair(currentRepair.id, values.rating, values.feedback)
      message.success('评价成功')
      logger.info('评价成功')
      setRateModalVisible(false)
      loadData()
    } catch (error) {
      logger.error('评价失败', error)
      message.error('评价失败')
    }
  }

  const getStatusColor = (status) => {
    const colorMap = {
      pending: 'orange',
      processing: 'blue',
      completed: 'green',
      cancelled: 'red'
    }
    return colorMap[status] || 'default'
  }

  const getStatusText = (status) => {
    const textMap = {
      pending: '待处理',
      processing: '处理中',
      completed: '已完成',
      cancelled: '已取消'
    }
    return textMap[status] || status
  }

  const columns = [
    {
      title: '报修标题',
      dataIndex: 'title',
      key: 'title',
      render: (text) => text || '-',
      width: 200
    },
    {
      title: '报修类型',
      dataIndex: 'repairType',
      key: 'repairType',
      render: (type) => {
        const typeMap = {
          water: '水管',
          electricity: '电路',
          appliance: '家电',
          other: '其他'
        }
        return typeMap[type] || type || '-'
      },
      width: 100
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      render: (status) => <Tag color={getStatusColor(status)}>{getStatusText(status) || '-'}</Tag>,
      width: 100
    },
    {
      title: '提交时间',
      dataIndex: 'createTime',
      key: 'createTime',
      render: (text) => text || '-',
      width: 180
    },
    {
      title: '操作',
      key: 'action',
      width: 200,
      fixed: 'right',
      render: (_, record) => (
        <div>
          {record.status === 'pending' && (
            <Button type="primary" danger size="small" onClick={() => handleCancel(record)}>
              取消报修
            </Button>
          )}
          {record.status === 'completed' && !record.rating && (
            <Button type="primary" size="small" icon={<StarOutlined />} onClick={() => handleRate(record)}>
              评价
            </Button>
          )}
          {record.rating && (
            <Tag color="gold">已评价 {record.rating}星</Tag>
          )}
        </div>
      )
    }
  ]

  return (
    <div style={{ padding: '24px', background: '#f5f7fa', minHeight: 'calc(100vh - 64px)' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <div>
          <h2 style={{ fontSize: '20px', fontWeight: 600, margin: 0, color: '#1f2937' }}>
            报修服务
          </h2>
          <p style={{ fontSize: '14px', color: '#6b7280', marginTop: '4px', margin: 0 }}>
            提交和管理您的报修申请
          </p>
        </div>
        <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
          申请报修
        </Button>
      </div>

      <Card 
        style={{ 
          borderRadius: '8px', 
          boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
          border: 'none'
        }}
      >
        <Table
          columns={columns}
          dataSource={repairs}
          rowKey="id"
          loading={loading}
          rowStyle={{ height: '60px' }}
          scroll={{ x: 780 }}
          pagination={{
            pageSize: 10,
            showSizeChanger: true,
            showTotal: (total) => `共 ${total} 条记录`
          }}
        />
      </Card>

      <Modal
        title="申请报修"
        open={addModalVisible}
        onOk={handleSubmitAdd}
        onCancel={() => setAddModalVisible(false)}
        okText="提交"
        cancelText="取消"
      >
        <Form form={form} layout="vertical">
          <Form.Item
            name="title"
            label="报修标题"
            rules={[{ required: true, message: '请输入报修标题' }]}
          >
            <Input placeholder="请输入报修标题" />
          </Form.Item>
          <Form.Item
            name="repairType"
            label="报修类型"
            rules={[{ required: true, message: '请选择报修类型' }]}
          >
            <Select placeholder="请选择报修类型">
              <Select.Option value="water">水管</Select.Option>
              <Select.Option value="electricity">电路</Select.Option>
              <Select.Option value="appliance">家电</Select.Option>
              <Select.Option value="other">其他</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item
            name="description"
            label="详细描述"
            rules={[{ required: true, message: '请输入详细描述' }]}
          >
            <Input.TextArea rows={4} placeholder="请详细描述报修内容" />
          </Form.Item>
          <Form.Item
            name="contactPhone"
            label="联系电话"
            rules={[{ required: true, message: '请输入联系电话' }]}
          >
            <Input placeholder="请输入联系电话" />
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        title="评价服务"
        open={rateModalVisible}
        onOk={handleSubmitRate}
        onCancel={() => setRateModalVisible(false)}
        okText="提交评价"
        cancelText="取消"
      >
        <Form form={rateForm} layout="vertical">
          <Form.Item
            name="rating"
            label="评分"
            rules={[{ required: true, message: '请选择评分' }]}
          >
            <Rate />
          </Form.Item>
          <Form.Item
            name="feedback"
            label="评价内容"
          >
            <Input.TextArea rows={4} placeholder="请输入评价内容" />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

export default Repair

// property-management/frontend/admin/src/views/repair/index.vue
<template>
  <div class="page-container">
    <el-card class="main-card">
      <template #header>
        <div class="card-header">
          <span class="title">报修管理</span>
        </div>
      </template>
      
      <el-form :inline="true" :model="queryParams" class="search-form">
        <el-form-item label="用户姓名">
          <el-input v-model="queryParams.userName" placeholder="请输入用户姓名" clearable style="width: 200px" />
        </el-form-item>
        <el-form-item label="报修类型">
          <el-select v-model="queryParams.repairType" placeholder="请选择报修类型" clearable style="width: 160px">
            <el-option label="水管" value="water" />
            <el-option label="电路" value="electricity" />
            <el-option label="家电" value="appliance" />
            <el-option label="其他" value="other" />
          </el-select>
        </el-form-item>
        <el-form-item label="状态">
          <el-select v-model="queryParams.status" placeholder="请选择状态" clearable style="width: 140px">
            <el-option label="待处理" value="pending" />
            <el-option label="处理中" value="processing" />
            <el-option label="已完成" value="completed" />
            <el-option label="已取消" value="cancelled" />
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="loadData">
            <el-icon style="margin-right: 4px"><Search /></el-icon>
            查询
          </el-button>
          <el-button @click="resetQuery">
            <el-icon style="margin-right: 4px"><RefreshLeft /></el-icon>
            重置
          </el-button>
        </el-form-item>
      </el-form>

      <el-table :data="tableData" v-loading="loading" style="width: 100%" :row-style="{ height: '60px' }">
        <el-table-column prop="userName" label="用户" width="100" />
        <el-table-column prop="userPhone" label="电话" width="130" />
        <el-table-column prop="projectName" label="项目" width="150" show-overflow-tooltip />
        <el-table-column prop="repairType" label="类型" width="80">
          <template #default="{ row }">
            <el-tag v-if="row.repairType === 'water'" type="info" size="small">水管</el-tag>
            <el-tag v-else-if="row.repairType === 'electricity'" type="warning" size="small">电路</el-tag>
            <el-tag v-else-if="row.repairType === 'appliance'" type="success" size="small">家电</el-tag>
            <el-tag v-else size="small">其他</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="title" label="标题" min-width="180" show-overflow-tooltip />
        <el-table-column prop="status" label="状态" width="90">
          <template #default="{ row }">
            <el-tag v-if="row.status === 'pending'" type="warning" size="small">待处理</el-tag>
            <el-tag v-else-if="row.status === 'processing'" type="primary" size="small">处理中</el-tag>
            <el-tag v-else-if="row.status === 'completed'" type="success" size="small">已完成</el-tag>
            <el-tag v-else-if="row.status === 'cancelled'" type="danger" size="small">已取消</el-tag>
            <el-tag v-else size="small">{{ row.status }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="200" fixed="right">
          <template #default="{ row }">
            <el-button type="primary" link size="small" @click="handleView(row)">查看</el-button>
            <el-button type="success" link size="small" v-if="row.status === 'pending'" @click="handleAssign(row)">派单</el-button>
            <el-button type="warning" link size="small" v-if="row.status === 'processing'" @click="handleComplete(row)">完成</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-model:current-page="queryParams.pageNum"
        v-model:page-size="queryParams.pageSize"
        :total="total"
        :page-sizes="[10, 20, 50, 100]"
        layout="total, sizes, prev, pager, next, jumper"
        @size-change="loadData"
        @current-change="loadData"
        style="margin-top: 20px; justify-content: flex-end"
      />
    </el-card>

    <el-dialog v-model="viewDialogVisible" title="报修详情" width="600px">
      <el-descriptions :column="1" border v-if="currentRow">
        <el-descriptions-item label="报修编号">{{ currentRow.repairNo || '-' }}</el-descriptions-item>
        <el-descriptions-item label="用户姓名">{{ currentRow.userName || '-' }}</el-descriptions-item>
        <el-descriptions-item label="联系电话">{{ currentRow.userPhone || '-' }}</el-descriptions-item>
        <el-descriptions-item label="项目名称">{{ currentRow.projectName || '-' }}</el-descriptions-item>
        <el-descriptions-item label="房屋信息">{{ currentRow.houseInfo || '-' }}</el-descriptions-item>
        <el-descriptions-item label="报修类型">
          <el-tag v-if="currentRow.repairType === 'water'" type="info">水管</el-tag>
          <el-tag v-else-if="currentRow.repairType === 'electricity'" type="warning">电路</el-tag>
          <el-tag v-else-if="currentRow.repairType === 'appliance'" type="success">家电</el-tag>
          <el-tag v-else>其他</el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="报修标题">{{ currentRow.title || '-' }}</el-descriptions-item>
        <el-descriptions-item label="详细描述">{{ currentRow.description || '-' }}</el-descriptions-item>
        <el-descriptions-item label="状态">
          <el-tag v-if="currentRow.status === 'pending'" type="warning">待处理</el-tag>
          <el-tag v-else-if="currentRow.status === 'processing'" type="primary">处理中</el-tag>
          <el-tag v-else-if="currentRow.status === 'completed'" type="success">已完成</el-tag>
          <el-tag v-else-if="currentRow.status === 'cancelled'" type="danger">已取消</el-tag>
          <el-tag v-else>{{ currentRow.status }}</el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="处理人">{{ currentRow.assigneeName || '-' }}</el-descriptions-item>
        <el-descriptions-item label="处理结果">{{ currentRow.result || '-' }}</el-descriptions-item>
        <el-descriptions-item label="用户评价" v-if="currentRow.rating">
          <el-rate v-model="currentRow.rating" disabled />
          <span style="margin-left: 10px">{{ currentRow.feedback || '-' }}</span>
        </el-descriptions-item>
        <el-descriptions-item label="提交时间">{{ currentRow.createTime || '-' }}</el-descriptions-item>
      </el-descriptions>
    </el-dialog>

    <el-dialog v-model="assignDialogVisible" title="派单" width="500px">
      <el-form :model="assignForm" label-width="80px">
        <el-form-item label="处理人">
          <el-select v-model="assignForm.assigneeName" placeholder="请选择处理人">
            <el-option label="系统管理员" value="系统管理员" />
            <el-option label="维修人员A" value="维修人员A" />
            <el-option label="维修人员B" value="维修人员B" />
          </el-select>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="assignDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitAssign">确定</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="completeDialogVisible" title="完成报修" width="500px">
      <el-form :model="completeForm" label-width="80px">
        <el-form-item label="处理结果">
          <el-input type="textarea" v-model="completeForm.result" :rows="4" placeholder="请输入处理结果" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="completeDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitComplete">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Search, RefreshLeft } from '@element-plus/icons-vue'
import { getRepairPage, assignRepair, completeRepair } from '@/api/repair'

const loading = ref(false)
const tableData = ref([])
const total = ref(0)
const queryParams = ref({
  pageNum: 1,
  pageSize: 10,
  userName: '',
  repairType: '',
  status: ''
})

const viewDialogVisible = ref(false)
const assignDialogVisible = ref(false)
const completeDialogVisible = ref(false)
const currentRow = ref(null)
const assignForm = ref({
  assigneeId: 1,
  assigneeName: ''
})
const completeForm = ref({
  result: ''
})

const loadData = async () => {
  loading.value = true
  try {
    const res = await getRepairPage(queryParams.value)
    if (res.code === 200) {
      tableData.value = res.data?.records || []
      total.value = res.data?.total || 0
    }
  } catch (error) {
    console.error('加载数据失败:', error)
    ElMessage.error('加载数据失败')
  } finally {
    loading.value = false
  }
}

const resetQuery = () => {
  queryParams.value = {
    pageNum: 1,
    pageSize: 10,
    userName: '',
    repairType: '',
    status: ''
  }
  loadData()
}

const handleView = (row) => {
  currentRow.value = row
  viewDialogVisible.value = true
}

const handleAssign = (row) => {
  currentRow.value = row
  assignForm.value = {
    assigneeId: 1,
    assigneeName: ''
  }
  assignDialogVisible.value = true
}

const submitAssign = async () => {
  if (!assignForm.value.assigneeName) {
    ElMessage.warning('请选择处理人')
    return
  }
  try {
    await assignRepair(currentRow.value.id, assignForm.value.assigneeId, assignForm.value.assigneeName)
    ElMessage.success('派单成功')
    assignDialogVisible.value = false
    loadData()
  } catch (error) {
    console.error('派单失败:', error)
    ElMessage.error('派单失败')
  }
}

const handleComplete = (row) => {
  currentRow.value = row
  completeForm.value = {
    result: ''
  }
  completeDialogVisible.value = true
}

const submitComplete = async () => {
  if (!completeForm.value.result) {
    ElMessage.warning('请输入处理结果')
    return
  }
  try {
    await completeRepair(currentRow.value.id, completeForm.value.result)
    ElMessage.success('操作成功')
    completeDialogVisible.value = false
    loadData()
  } catch (error) {
    console.error('操作失败:', error)
    ElMessage.error('操作失败')
  }
}

onMounted(() => {
  loadData()
})
</script>

<style lang="scss" scoped>
.page-container {
  .main-card {
    border: none;
    border-radius: 8px;
  }
  
  .card-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    
    .title {
      font-size: 18px;
      font-weight: 600;
      color: #1f2937;
    }
  }
  
  .search-form {
    padding: 20px 0;
    border-bottom: 1px solid #f0f0f0;
    margin-bottom: 16px;
  }
  
  :deep(.el-card) {
    --el-card-border-radius: 8px;
  }
  
  :deep(.el-table) {
    .el-table__header-wrapper {
      th {
        background: #fafafa;
        color: #606266;
        font-weight: 600;
      }
    }
    
    .el-table__body-wrapper {
      .el-table__row {
        &:hover > td {
          background: #fafafa !important;
        }
      }
    }
  }
}
</style>
