// property-management/frontend/admin/src/views/login/index.vue
<template>
  <div class="login-container">
    <div class="login-box">
      <h2 class="title">物业管理系统</h2>
      <el-form :model="loginForm" :rules="rules" ref="formRef">
        <el-form-item prop="username">
          <el-input v-model="loginForm.username" placeholder="请输入手机号" prefix-icon="User" />
        </el-form-item>
        <el-form-item prop="password">
          <el-input v-model="loginForm.password" type="password" placeholder="请输入密码" prefix-icon="Lock" show-password @keyup.enter="handleLogin" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleLogin" :loading="loading" style="width: 100%">登录</el-button>
        </el-form-item>
      </el-form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import type { FormInstance, FormRules } from 'element-plus'
import { login } from '@/api/user'
import { useUserStore } from '@/stores/user'
import { logger } from '@/utils/request'
import { encodeToken } from '@/utils/base64'
import type { User, ApiResponse } from '@/types'

const router = useRouter()
const userStore = useUserStore()
const formRef = ref<FormInstance>()
const loading = ref(false)

const loginForm = reactive({
  username: '',
  password: ''
})

const rules: FormRules = {
  username: [
    { required: true, message: '请输入手机号', trigger: 'blur' },
    { pattern: /^1[3-9]\d{9}$/, message: '请输入正确的手机号', trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' },
    { min: 6, message: '密码长度不能少于6位', trigger: 'blur' }
  ]
}

const handleLogin = async () => {
  if (!formRef.value) return
  
  try {
    await formRef.value.validate()
  } catch (error) {
    logger.warn('登录表单验证失败', error)
    return
  }
  
  loading.value = true
  logger.info('开始登录请求', { phone: loginForm.username })
  
  try {
    const res = await login({ phone: loginForm.username, password: loginForm.password })
    
    if (!res || !res.data) {
      logger.error('登录响应数据为空')
      ElMessage.error('登录失败：服务器响应异常')
      return
    }
    
    const userInfo = res.data
    console.log('后端返回的用户信息:', userInfo)
    console.log('用户类型:', userInfo.userType)
    
    userStore.setUserInfo(userInfo)
    const token = encodeToken({ userId: userInfo.id, username: userInfo.realName, userType: userInfo.userType })
    userStore.setToken(token)
    
    logger.info('登录成功', { userId: userInfo.id, userName: userInfo.realName, userType: userInfo.userType })
    ElMessage.success('登录成功')
    router.push('/')
  } catch (error: unknown) {
    logger.error('登录失败', error)
    
    if (error instanceof Error) {
      ElMessage.error(error.message)
    } else {
      ElMessage.error('登录失败，请稍后重试')
    }
  } finally {
    loading.value = false
  }
}
</script>

<style lang="scss" scoped>
.login-container {
  width: 100%;
  height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);

  .login-box {
    width: 400px;
    padding: 40px;
    background: #fff;
    border-radius: 8px;
    box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);

    .title {
      text-align: center;
      margin-bottom: 30px;
      color: #303133;
    }
  }
}
</style>

// property-management/frontend/owner/src/pages/login/index.tsx
import { Form, Input, Button, Card, message } from 'antd'
import { UserOutlined, LockOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { login } from '../../api'
import { useUserStore } from '../../stores/user'
import { encodeToken } from '../../utils/base64'
import type { User } from '../../types'
import './login.css'

interface LoginFormValues {
  phone: string
  password: string
}

function Login() {
  const navigate = useNavigate()
  const setToken = useUserStore((state) => state.setToken)
  const setUserInfo = useUserStore((state) => state.setUserInfo)
  const [form] = Form.useForm()

  const handleSubmit = async (values: LoginFormValues) => {
    try {
      const res = await login(values) as unknown as { data: User }
      
      if (!res || !res.data) {
        message.error('登录失败：服务器响应异常')
        return
      }
      
      const userInfo = res.data
      const token = encodeToken({ userId: userInfo.id, username: userInfo.realName || userInfo.username, userType: userInfo.userType })
      setToken(token)
      setUserInfo(userInfo)
      
      message.success('登录成功')
      navigate('/')
    } catch (error) {
      if (error instanceof Error) {
        message.error(error.message)
      } else {
        message.error('登录失败，请稍后重试')
      }
    }
  }

  return (
    <div className="login-container">
      <Card className="login-card" title="智慧物业 - 业主端">
        <Form 
          form={form} 
          onFinish={handleSubmit}
          size="large"
        >
          <Form.Item 
            name="phone" 
            rules={[
              { required: true, message: '请输入手机号' },
              { pattern: /^1[3-9]\d{9}$/, message: '请输入正确的手机号' }
            ]}
          >
            <Input prefix={<UserOutlined />} placeholder="请输入手机号" />
          </Form.Item>
          <Form.Item 
            name="password" 
            rules={[
              { required: true, message: '请输入密码' },
              { min: 6, message: '密码长度不能少于6位' }
            ]}
          >
            <Input.Password prefix={<LockOutlined />} placeholder="请输入密码" />
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" block>登录</Button>
          </Form.Item>
        </Form>
      </Card>
    </div>
  )
}

export default Login
