// property-management/frontend/owner/src/pages/fee/index.jsx
import { useState, useEffect } from 'react'
import { Card, Table, Tag, Button, Modal, Radio, message } from 'antd'
import { PayCircleOutlined } from '@ant-design/icons'
import { useUserStore } from '../../stores/user'
import { getFeesByUser, payFee } from '../../api'
import { logger } from '../../utils/request'

function Fee() {
  const { userInfo } = useUserStore()
  const [fees, setFees] = useState([])
  const [loading, setLoading] = useState(false)
  const [payModalVisible, setPayModalVisible] = useState(false)
  const [currentFee, setCurrentFee] = useState(null)
  const [payMethod, setPayMethod] = useState('wechat')

  useEffect(() => {
    if (userInfo?.id) {
      loadData()
    }
  }, [userInfo?.id])

  const loadData = async () => {
    if (!userInfo?.id) {
      logger.warn('用户信息不存在，无法加载费用数据')
      return
    }

    setLoading(true)
    logger.info('开始加载费用信息', { userId: userInfo.id })

    try {
      const res = await getFeesByUser(userInfo.id)
      setFees(res.data || [])
      logger.info('费用信息加载成功', { count: res.data?.length || 0 })
    } catch (error) {
      logger.error('加载费用信息失败:', error)
      message.error('加载费用信息失败，请稍后重试')
    } finally {
      setLoading(false)
    }
  }

  const handlePay = (fee) => {
    setCurrentFee(fee)
    setPayModalVisible(true)
  }

  const handleConfirmPay = async () => {
    try {
      logger.info('开始缴费', { feeId: currentFee.id, payMethod })
      await payFee(currentFee.id, payMethod)
      message.success('缴费成功')
      logger.info('缴费成功', { feeId: currentFee.id })
      setPayModalVisible(false)
      loadData()
    } catch (error) {
      logger.error('缴费失败', error)
      message.error('缴费失败')
    }
  }

  const columns = [
    {
      title: '费用名称',
      dataIndex: 'feeName',
      key: 'feeName',
      render: (text) => text || '-',
      width: 180
    },
    {
      title: '费用类型',
      dataIndex: 'feeType',
      key: 'feeType',
      render: (type) => {
        const typeMap = {
          property: '物业费',
          water: '水费',
          electricity: '电费',
          parking: '停车费'
        }
        return typeMap[type] || type || '-'
      },
      width: 100
    },
    {
      title: '金额',
      dataIndex: 'amount',
      key: 'amount',
      render: (amount) => amount !== undefined ? `¥${amount}` : '-',
      width: 120
    },
    {
      title: '计费周期',
      dataIndex: 'billingPeriod',
      key: 'billingPeriod',
      render: (text) => text || '-',
      width: 140
    },
    {
      title: '截止日期',
      dataIndex: 'dueDate',
      key: 'dueDate',
      render: (text) => text || '-',
      width: 140
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      render: (status) => {
        const colorMap = {
          unpaid: 'red',
          paid: 'green',
          overdue: 'orange'
        }
        const textMap = {
          unpaid: '未支付',
          paid: '已支付',
          overdue: '已逾期'
        }
        return <Tag color={colorMap[status]}>{textMap[status] || status || '-'}</Tag>
      },
      width: 100
    },
    {
      title: '操作',
      key: 'action',
      width: 140,
      fixed: 'right',
      render: (_, record) => (
        record.status === 'unpaid' || record.status === 'overdue' ? (
          <Button type="primary" size="small" icon={<PayCircleOutlined />} onClick={() => handlePay(record)}>
            立即缴费
          </Button>
        ) : (
          <Button type="default" size="small" disabled>
            已支付
          </Button>
        )
      )
    }
  ]

  return (
    <div style={{ padding: '24px', background: '#f5f7fa', minHeight: 'calc(100vh - 64px)' }}>
      <div style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '20px', fontWeight: 600, margin: 0, color: '#1f2937' }}>
          费用缴纳
        </h2>
        <p style={{ fontSize: '14px', color: '#6b7280', marginTop: '4px', margin: 0 }}>
          查看并缴纳您的各项物业费用
        </p>
      </div>
      
      <Card 
        style={{ 
          borderRadius: '8px', 
          boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
          border: 'none'
        }}
      >
        <Table
          columns={columns}
          dataSource={fees}
          rowKey="id"
          loading={loading}
          rowStyle={{ height: '60px' }}
          scroll={{ x: 920 }}
          pagination={{
            pageSize: 10,
            showSizeChanger: true,
            showTotal: (total) => `共 ${total} 条记录`
          }}
        />
      </Card>

      <Modal
        title="在线缴费"
        open={payModalVisible}
        onOk={handleConfirmPay}
        onCancel={() => setPayModalVisible(false)}
        okText="确认支付"
        cancelText="取消"
      >
        {currentFee && (
          <div>
            <p><strong>费用名称：</strong>{currentFee.feeName}</p>
            <p><strong>费用金额：</strong>¥{currentFee.amount}</p>
            <p><strong>支付方式：</strong></p>
            <Radio.Group value={payMethod} onChange={(e) => setPayMethod(e.target.value)}>
              <Radio value="wechat">微信支付</Radio>
              <Radio value="alipay">支付宝</Radio>
              <Radio value="bank">银行卡</Radio>
            </Radio.Group>
          </div>
        )}
      </Modal>
    </div>
  )
}

export default Fee

// property-management/frontend/admin/src/views/fee/index.vue
<template>
  <div class="page-container">
    <el-card class="main-card">
      <template #header>
        <div class="card-header">
          <span class="title">费用管理</span>
          <el-button type="primary" @click="handleAdd">
            <el-icon style="margin-right: 4px"><Plus /></el-icon>
            新增
          </el-button>
        </div>
      </template>
      
      <el-form :inline="true" :model="queryParams" class="search-form">
        <el-form-item label="费用类型">
          <el-select v-model="queryParams.feeType" placeholder="请选择费用类型" clearable style="width: 160px">
            <el-option label="物业费" value="property" />
            <el-option label="水费" value="water" />
            <el-option label="电费" value="electricity" />
            <el-option label="停车费" value="parking" />
          </el-select>
        </el-form-item>
        <el-form-item label="状态">
          <el-select v-model="queryParams.status" placeholder="请选择状态" clearable style="width: 140px">
            <el-option label="未支付" value="unpaid" />
            <el-option label="已支付" value="paid" />
            <el-option label="已逾期" value="overdue" />
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="loadData">
            <el-icon style="margin-right: 4px"><Search /></el-icon>
            查询
          </el-button>
          <el-button @click="resetQuery">
            <el-icon style="margin-right: 4px"><RefreshLeft /></el-icon>
            重置
          </el-button>
        </el-form-item>
      </el-form>

      <el-table :data="tableData" v-loading="loading" style="width: 100%" :row-style="{ height: '60px' }">
        <el-table-column prop="feeName" label="费用名称" width="140" show-overflow-tooltip />
        <el-table-column prop="feeType" label="类型" width="100">
          <template #default="{ row }">
            <el-tag v-if="row.feeType === 'property'" type="info" size="small">物业费</el-tag>
            <el-tag v-else-if="row.feeType === 'water'" type="primary" size="small">水费</el-tag>
            <el-tag v-else-if="row.feeType === 'electricity'" type="warning" size="small">电费</el-tag>
            <el-tag v-else-if="row.feeType === 'parking'" type="success" size="small">停车费</el-tag>
            <el-tag v-else size="small">{{ row.feeType }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="amount" label="金额" width="100">
          <template #default="{ row }">
            ¥{{ row.amount }}
          </template>
        </el-table-column>
        <el-table-column prop="billingPeriod" label="计费周期" width="140" show-overflow-tooltip />
        <el-table-column prop="dueDate" label="截止日期" width="120" />
        <el-table-column prop="status" label="状态" width="90">
          <template #default="{ row }">
            <el-tag v-if="row.status === 'unpaid'" type="danger" size="small">未支付</el-tag>
            <el-tag v-else-if="row.status === 'paid'" type="success" size="small">已支付</el-tag>
            <el-tag v-else-if="row.status === 'overdue'" type="warning" size="small">已逾期</el-tag>
            <el-tag v-else size="small">{{ row.status }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="130" fixed="right">
          <template #default="{ row }">
            <el-button type="primary" link size="small">编辑</el-button>
            <el-button type="danger" link size="small">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-model:current-page="queryParams.pageNum"
        v-model:page-size="queryParams.pageSize"
        :total="total"
        :page-sizes="[10, 20, 50, 100]"
        layout="total, sizes, prev, pager, next, jumper"
        @size-change="loadData"
        @current-change="loadData"
        style="margin-top: 20px; justify-content: flex-end"
      />
    </el-card>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { Search, RefreshLeft, Plus } from '@element-plus/icons-vue'
import { getFeePage } from '@/api/fee'

const loading = ref(false)
const tableData = ref([])
const total = ref(0)
const queryParams = ref({
  pageNum: 1,
  pageSize: 10,
  feeType: '',
  status: ''
})

const loadData = async () => {
  loading.value = true
  try {
    const res = await getFeePage(queryParams.value)
    if (res.code === 200) {
      tableData.value = res.data?.records || []
      total.value = res.data?.total || 0
    }
  } catch (error) {
    console.error('加载数据失败:', error)
    ElMessage.error('加载数据失败')
  } finally {
    loading.value = false
  }
}

const resetQuery = () => {
  queryParams.value = {
    pageNum: 1,
    pageSize: 10,
    feeType: '',
    status: ''
  }
  loadData()
}

const handleAdd = () => {
  ElMessage.info('新增功能')
}

onMounted(() => {
  loadData()
})
</script>

<style lang="scss" scoped>
.page-container {
  .main-card {
    border: none;
    border-radius: 8px;
  }
  
  .card-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    
    .title {
      font-size: 18px;
      font-weight: 600;
      color: #1f2937;
    }
  }
  
  .search-form {
    padding: 20px 0;
    border-bottom: 1px solid #f0f0f0;
    margin-bottom: 16px;
  }
  
  :deep(.el-card) {
    --el-card-border-radius: 8px;
  }
  
  :deep(.el-table) {
    .el-table__header-wrapper {
      th {
        background: #fafafa;
        color: #606266;
        font-weight: 600;
      }
    }
    
    .el-table__body-wrapper {
      .el-table__row {
        &:hover > td {
          background: #fafafa !important;
        }
      }
    }
  }
}
</style>
